Portfolio Management - Customer Portal/CustomerPortal/Controllers/PortfolioController.cs
using CustomerPortal.Models;
using CustomerPortal.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Linq;

namespace CustomerPortal.Controllers
{
    /// <summary>
    /// Provides methods that respond to HTTP requests for portfolio controller
    /// </summary>
    public class PortfolioController : Controller
    {
        /// <summary>
        /// Portfolio service
        /// </summary>
        private readonly IPortfolioService portfolioService;

        /// <summary>
        /// Logger service
        /// </summary>
        private readonly ILogger<PortfolioController> logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="PortfolioController"/> class
        /// </summary>
        /// <param name="portfolioService">Portfolio service</param>
        /// <param name="logger">Logger service</param>
        public PortfolioController(IPortfolioService portfolioService,ILogger<PortfolioController> logger)
        {
            this.logger = logger;
            this.portfolioService = portfolioService;
        }

        /// <summary>
        /// Sell assets
        /// </summary>
        /// <param name="assetName">Asset name</param>
        /// <param name="id">Asset id</param>
        /// <param name="assetType">Asset type</param>
        /// <returns></returns>
        public IActionResult SellAssets(string assetName,int id,string assetType)
        {
            PortfolioDetails portfolioDetails = this.portfolioService.GetCustomerPortfolio(id);
            AssetSaleResponse assetSaleResponse = this.portfolioService.SellAsset(portfolioDetails,assetName,assetType);
            if(assetSaleResponse != null)
            {
                if(assetSaleResponse.SaleStatus == true)
                {                  
                    portfolioDetails.NetWorth = assetSaleResponse.Networth;
                    RemoveAsset(portfolioDetails, assetType, assetName);
                    logger.LogInformation($"{assetName} sold from portfolio with portfolioId {portfolioDetails.PortfolioId}");
                    return View("GetCustomerPortfolio", portfolioDetails);
                }
            }
            logger.LogInformation($"Error while selling assets");
            return StatusCode(500, "Asset cannot be sold now");
        }

        /// <summary>
        /// Get customer portfolio
        /// </summary>
        /// <param name="portfolioId">Portfolio id</param>
        /// <returns>Customer portfolio page</returns>
        public IActionResult GetCustomerPortfolio(int portfolioId)
        {
            PortfolioDetails portfolioDetails = this.portfolioService.GetCustomerPortfolio(portfolioId);
            this.logger.LogInformation($"retrieving portfolio details of user with portfolioId {portfolioDetails.PortfolioId}");
            return View(portfolioDetails);
        }

        /// <summary>
        /// Remove asset
        /// </summary>
        /// <param name="portfolioDetails">Portfolio details</param>
        /// <param name="assetType">Asset type</param>
        /// <param name="assetName">Asset name</param>
        private static void RemoveAsset(PortfolioDetails portfolioDetails, string assetType, string assetName)
        {
            if(assetType.Equals(AssetType.Stock))
            {
                StockDetails stockToBeDeleted = portfolioDetails.StockList.FirstOrDefault(x => x.StockName == assetName);
                portfolioDetails.StockList.Remove(stockToBeDeleted);
            }
            else
            {
                MutualFundDetails mutualFundToBeDeleted = portfolioDetails.MutualFundList.FirstOrDefault(x => x.MutualFundName == assetName);
                portfolioDetails.MutualFundList.Remove(mutualFundToBeDeleted);
            }
        }
    }
}

Portfolio Management - Customer Portal/CustomerPortal/Views/Portfolio/GetCustomerPortfolio.cshtml
@model CustomerPortal.Models.PortfolioDetails

@{
    Layout = "_Layout";
}


<div class="container">
    <h4 class="display-4">Portfolio Networth : INR @Model.NetWorth</h4>
    <div class="row">
        <br />
        <h4><i> Stocks owned</i></h4>
       

            @foreach (var stock in Model.StockList)
            {
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm" style="width: 18rem;">
                        <img class="card-img-top" src="~/Images/dummy.jpg" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">@stock.StockName</h5>
                            <p class="card-text"> @stock.StockCount</p>
                            <a asp-controller="Portfolio" asp-action="SellAssets" asp-route-assetName="@stock.StockName" asp-route-id="@Model.PortfolioId" asp-route-assetType="Stock" class="btn btn-primary">Sell Asset</a>
                            <!--  <small class="text-muted"> </small>-->
                        </div>
                    </div>
                </div>
            }

        </div>
     
    <div class="row">
        <br />
        <h4><i>Mutual Funds owned</i> </h4>
     
            @foreach (var mutualFund in Model.MutualFundList)
            {
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm" style="width: 18rem;">
                        <img class="card-img-top" src="~/Images/dummy.jpg" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">@mutualFund.MutualFundName</h5>
                            <p class="card-text"> @mutualFund.MutualFundUnits</p>
                            <a asp-controller="Portfolio" asp-action="SellAssets" asp-route-assetName="@mutualFund.MutualFundName" asp-route-id="@Model.PortfolioId" asp-route-assetType="MutualFund" class="btn btn-primary">Sell Asset</a>
                            <!--  <small class="text-muted"> </small>-->
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>

Portfolio Management - Customer Portal/CustomerPortal/Views/Portfolio/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand text-info" href="#">

                    <img src="~/Images/logo.png" height="30" width="30" />
                    <b><i>Portfolio</i></b>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Account" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item text-info">
                            <a class="nav-link text-info" href="#">Stocks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" href="#">Mutual Funds</a>
                        </li>
                    </ul>
                    <ul class="navbar nav">
                        <li class="nav-item">
                            <a class="btn btn-outline-info" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>
</html>